# -*- mode: ruby -*-
Vagrant.configure("2") do |config|
    config.ssh.insert_key = false
    config.vm.box_download_options={"tls-max": "1.2"}

    # Control Plane 
    config.vm.define "cplane" do |cp|
      cp.vm.hostname = "cplane"
      cp.vm.box = "bento/ubuntu-20.04"
      cp.vm.network "private_network", ip: "192.168.0.10"

      cp.vm.provider "virtualbox" do |vb|
          vb.name = 'cplane'
          vb.memory = 8192
          vb.cpus = 4
        end
      cp.vm.provision "shell", path: "scripts/common.sh"
      cp.vm.provision "file", source: "files/10-containerd-net.conflist", destination: "/home/vagrant/10-containerd-net.conflist"
    end
    
    # Worker Node 1
    config.vm.define "worker01" do |wn|
      wn.vm.hostname = "worker01"
      wn.vm.box = "bento/ubuntu-20.04"
      wn.vm.network "private_network", ip: "192.168.0.11"

      wn.vm.provider "virtualbox" do |vb|
          vb.name = 'worker01'
          vb.memory = 8192
          vb.cpus = 4
        end
      wn.vm.provision "shell",
        path: "scripts/common.sh"
    end

    # Worker Node 2
    config.vm.define "worker02" do |wn|
      wn.vm.hostname = "worker02"
      wn.vm.box = "bento/ubuntu-20.04"
      wn.vm.network "private_network", ip: "192.168.0.12"

      wn.vm.provider "virtualbox" do |vb|
          vb.name = 'worker02'
          vb.memory = 8192
          vb.cpus = 4
        end
      wn.vm.provision "shell",
        path: "scripts/common.sh"
    end
end