# -*- mode: ruby -*-
Vagrant.configure("2") do |config|
    config.ssh.insert_key = false
    config.vm.box_download_options={"tls-max": "1.2"}

    # Control Plane 
    config.vm.define "cplane.kube" do |cp|
      cp.vm.hostname = "cplane.kube"
      cp.vm.box = "bento/ubuntu-22.04"
      cp.vm.network "private_network", ip: "192.168.0.10"

      cp.vm.provider "virtualbox" do |vb|
          vb.name = 'k8scplane'
          vb.memory = 4096
          vb.cpus = 2
        end
      cp.vm.provision "shell",
      path: "scripts/common.sh"
    end
    
    # Worker Node 1
    config.vm.define "worker01.kube" do |wn|
      wn.vm.hostname = "worker01.kube"
      wn.vm.box = "bento/ubuntu-22.04"
      wn.vm.network "private_network", ip: "192.168.0.11"

      wn.vm.provider "virtualbox" do |vb|
          vb.name = 'worker01'
          vb.memory = 4096
          vb.cpus = 2
        end
      wn.vm.provision "shell",
        path: "scripts/common.sh"
    end

    # Worker Node 2
    config.vm.define "worker02.kube" do |wn|
      wn.vm.hostname = "worker02.kube"
      wn.vm.box = "bento/ubuntu-22.04"
      wn.vm.network "private_network", ip: "192.168.0.12"

      wn.vm.provider "virtualbox" do |vb|
          vb.name = 'worker02'
          vb.memory = 4096
          vb.cpus = 2
        end
      wn.vm.provision "shell",
        path: "scripts/common.sh"
    end
end